---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - uwsgi
    - uwsgi-plugin-python

#TODO test nginx default site is working
#

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: Copy app nginx site config
  template: src=summit.j2 dest=/etc/nginx/sites-available/summit owner=root group=root mode=0644
  notify:
    - restart nginx

- name: Enable app nginx site config
  file: src=/etc/nginx/sites-available/summit dest=/etc/nginx/sites-enabled/summit state=link
  notify:
    - restart nginx
