---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - bzr
    - python2.7
    #- python2.7-dev
    - python-virtualenv
    - libjs-jquery
    - libjs-jquery-ui
    - iso-codes
    - python-django
    - python-django-auth-openid
    - python-django-south
    - python-beautifulsoup
    - python-psycopg2
    - python-openid
    - python-tz
    - python-simplejson
    - python-markdown

- name: Create summit user
  user: name=summit state=present

- include: ./app.yml user=summit

- name: Copy uwsgi config
  template: src=uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/summit.ini
  notify:
    - restart summit

- name: Enable uwsgi config
  file: src=/etc/uwsgi/apps-available/summit.ini dest=/etc/uwsgi/apps-enabled/summit.ini state=link
  notify:
    - restart summit

- name: Copy supervisord config
  template: src=supervisord_uwsgi.conf.j2 dest=/etc/supervisor/conf.d/summit.conf owner=root group=root mode=0644
  notify:
    - reload supervisord
    - restart summit

- name: Start django app
  supervisorctl: name=summit state=started
